/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTriagemInicialRouteImport } from './routes/_app.triagem-inicial'
import { Route as AppTotemRouteImport } from './routes/_app.totem'
import { Route as AppPainelRouteImport } from './routes/_app.painel'
import { Route as AppConfigRouteImport } from './routes/_app.config'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppTriagensSourceIdRouteImport } from './routes/_app.triagens.$source.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTriagemInicialRoute = AppTriagemInicialRouteImport.update({
  id: '/triagem-inicial',
  path: '/triagem-inicial',
  getParentRoute: () => AppRoute,
} as any)
const AppTotemRoute = AppTotemRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppTriagensSourceIdRoute = AppTriagensSourceIdRouteImport.update({
  id: '/triagens/$source/$id',
  path: '/triagens/$source/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/config': typeof AppConfigRoute
  '/painel': typeof AppPainelRoute
  '/totem': typeof AppTotemRoute
  '/triagem-inicial': typeof AppTriagemInicialRoute
  '/triagens/$source/$id': typeof AppTriagensSourceIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/config': typeof AppConfigRoute
  '/painel': typeof AppPainelRoute
  '/totem': typeof AppTotemRoute
  '/triagem-inicial': typeof AppTriagemInicialRoute
  '/': typeof AppIndexRoute
  '/triagens/$source/$id': typeof AppTriagensSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/painel': typeof AppPainelRoute
  '/_app/totem': typeof AppTotemRoute
  '/_app/triagem-inicial': typeof AppTriagemInicialRoute
  '/_app/': typeof AppIndexRoute
  '/_app/triagens/$source/$id': typeof AppTriagensSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/config'
    | '/painel'
    | '/totem'
    | '/triagem-inicial'
    | '/triagens/$source/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/config'
    | '/painel'
    | '/totem'
    | '/triagem-inicial'
    | '/'
    | '/triagens/$source/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/config'
    | '/_app/painel'
    | '/_app/totem'
    | '/_app/triagem-inicial'
    | '/_app/'
    | '/_app/triagens/$source/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triagem-inicial': {
      id: '/_app/triagem-inicial'
      path: '/triagem-inicial'
      fullPath: '/triagem-inicial'
      preLoaderRoute: typeof AppTriagemInicialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/totem': {
      id: '/_app/totem'
      path: '/totem'
      fullPath: '/totem'
      preLoaderRoute: typeof AppTotemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel': {
      id: '/_app/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triagens/$source/$id': {
      id: '/_app/triagens/$source/$id'
      path: '/triagens/$source/$id'
      fullPath: '/triagens/$source/$id'
      preLoaderRoute: typeof AppTriagensSourceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppConfigRoute: typeof AppConfigRoute
  AppPainelRoute: typeof AppPainelRoute
  AppTotemRoute: typeof AppTotemRoute
  AppTriagemInicialRoute: typeof AppTriagemInicialRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTriagensSourceIdRoute: typeof AppTriagensSourceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppConfigRoute: AppConfigRoute,
  AppPainelRoute: AppPainelRoute,
  AppTotemRoute: AppTotemRoute,
  AppTriagemInicialRoute: AppTriagemInicialRoute,
  AppIndexRoute: AppIndexRoute,
  AppTriagensSourceIdRoute: AppTriagensSourceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
